from .terms import PseudoColumn

ColumnValue: PseudoColumn = ...
ObjectID: PseudoColumn = ...
ObjectValue: PseudoColumn = ...
RowNum: PseudoColumn = ...
RowID: PseudoColumn = ...
SysDate: PseudoColumn = ...
