from pypika import CustomFunction as CustomFunction

ToYYYYMM: CustomFunction = ...
AddYears: CustomFunction = ...
AddMonths: CustomFunction = ...
AddWeeks: CustomFunction = ...
AddDays: CustomFunction = ...
AddHours: CustomFunction = ...
AddMinutes: CustomFunction = ...
AddSeconds: CustomFunction = ...
AddQuarters: CustomFunction = ...
SubtractYears: CustomFunction = ...
SubtractMonths: CustomFunction = ...
SubtractWeeks: CustomFunction = ...
SubtractDays: CustomFunction = ...
SubtractHours: CustomFunction = ...
SubtractMinutes: CustomFunction = ...
SubtractSeconds: CustomFunction = ...
SubtractQuarters: CustomFunction = ...
FormatDateTime: CustomFunction = ...
